backend:
  name: github
  repo: Dzee97/website-meike
  branch: main
  base_url: https://decap-oauth.df-zee.workers.dev

publish_mode: editorial_workflow
media_folder: "public/uploads"
public_folder: "/uploads"

collections:

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "experience"
    label: "Experience"
    folder: "src/content/experience"
    create: true
    slug: "{{slug}}"

    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Organization", name: "organization", widget: "string"}
      - {label: "Period", name: "period", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Description", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"

    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Description", name: "body", widget: "markdown"}